name: Build

on:
  push:
    branches: "**"
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  release:
    name: playground build pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # TODO: Will be changed into install dependencies
      - name: Install cppcheck
        run: |
             sudo apt-get update
             sudo apt-get install cppcheck

      - name: Build project
        run: |
            ./scripts/build.sh
