name: Build

on:
  push:
    branches: "**"
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  release:
    name: playground build pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: |
            .${{github.workspace}}/scripts/build.sh
